// User
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
//SETTINGS
export const GET_SETTINGS = "GET_SETTINGS";
export const DIALOGS_SET_NOREAD = "DIALOGS_SET_NOREAD";
export const GEOARTICLE_SET_LOCATION = "GEOARTICLE_SET_LOCATION";
export const NOTIFICATIONS_NOREAD_GET = "NOTIFICATIONS_NOREAD_GET";
export const NOTIFICATIONS_READ_ALL = "NOTIFICATIONS_READ_ALL";
